; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif32
framework = arduino, espidf

; General build flags apply to all environments.
build_flags =
    -D CONFIG_BLINK_GPIO=16 ; Pin used for the blink example
monitor_speed = 115200 ; Standard baud rate for monitoring



; ----------------------------------------------------
; Specific Environment for Freenove ESP32 WROOM
; ----------------------------------------------------
[env:freenove_wroom]
; 'esp32dev' is the standard, most compatible board definition for generic WROOM modules.
board = esp32dev 
upload_port = /dev/ttyUSB0 ; The serial port we successfully mapped from the host
monitor_port = /dev/ttyUSB0

; Lib dependencies
lib_deps = 
    bblanchon/ArduinoJson @ ^7.4.2
    knolleary/PubSubClient @ ^2.8
    adafruit/DHT sensor library @ ^1.4.6
;